### ISSUE TITLE
Core dev sprint sponsorship prospectus

### ISSUE THREAD

**Issue by Mariatta** [python/core-sprint#10]
Sponsorship prospectus for the core dev sprints

Ewa to bring up on Monday to the SC

Can be a 10 min slot for organizations to address core devs

These funds can be used to send F&B allowances to core devs attending the sprint, could also be used to pay for the fun activities (such as virtual escape room)

**Comment by ejodlowska** [comment]
I will have a draft sponsorship prospectus prepared by the end of this week for us to review. The SC is onboard with the idea as long as it is phrased appropriately. After the three of us review it, I will also share it with the board fundraising committee for input before it is published.

**Comment by taleinat** [comment]
Any updates on this?

**Comment by ejodlowska** [comment]
This has been set in motion a couple weeks back. The original host org is trying to make it work but in the meantime, we are sending out to contacts. If you have an org in mind for this @taleinat, feel free to ping me. Mariatta, Kyle and I are hoping to offer stipends to core devs for the week of the sprints and this sponsorship would help make that happen.
