### ISSUE TITLE
Plan social and fun activities

### ISSUE THREAD

**Issue by Mariatta** [python/core-sprint#12]
Schedule some fun and social activities.

Perhaps poll core devs on 7 activities and pick the top 3

Some suggested activities:
- virtual escape room
- group pixel drawing
- https://gather.town/
- online board games
- virtual lunch/ coffee break
- ???

**Comment by corona10** [comment]
> https://gather.town/

I think that we could take group photos on not only zoom but also on `https://gather.town/`

**Comment by aeros** [comment]
The upcoming signup form includes a section on social activities (including @corona10's mention of Gather), where participants will be able to select as many as they would be potentially interested in. We could potentially post the results in here and use them to structure the social activities.

**Comment by Mariatta** [comment]
Based on current signups, the most popular voted social activities are:
- unstructured social time
- board games
- escape room

I will be researching a few options for escape room for the group. Kyle will be researching board games/ games within Discord.
For unstructured social time, we will create a dedicated "break room" channel within Discord. We will also schedule "lunch break" every day.

**Comment by brainwane** [comment]
I just saw this and wanted to let you know about [Imaginary Book Club](https://www.harihareswara.net/sumana/2020/08/26/0) which can be a fun group improv game.
