### ISSUE TITLE
Sprint activity: all hands kickoff and sendoff 

### ISSUE THREAD

**Issue by Mariatta** [python/core-sprint#14]
Suggestion from @brainwane on [Discourse](https://discuss.python.org/t/2020-core-dev-sprint-virtual-sprinting-sessions/3947/16):

**Two big (short) all-hands meetings: kickoff and sendoff** – If people trickle in at the start and out at the end without a clear start and end to the sprint, then participants miss opportunities to catch each other, feel less connected, and miss logistical reminders. So: schedule a simultaneous all-hands chat for the kickoff (probably 10 minutes on logistics and 10 minutes summarizing what teams are working on what), and a call for the end of the last day (20 minutes on accomplishments and next steps).

**Comment by Mariatta** [comment]
Do we want "live" all hands, or just pre-record the announcement and let people watch it whenever they start the sprint?

**Comment by terryjreedy** [comment]
Both.  I like the idea of a live start, but record for people who cannot make it.

**Comment by Mariatta** [comment]
We've scheduled the kick-off to be on Monday 9 AM US Pacific, and Friday 9 AM US Pacific. [Schedule](https://python-core-sprint-2020.readthedocs.io/schedule.html) page has been updated with this information.

**Comment by taleinat** [comment]
> Schedule page has been updated with this information.

@Mariatta, a friendly reminder to add these to the shared event calendar :)

**Comment by Mariatta** [comment]
I've created the event and everyone should have received invites. Thanks!
