### ISSUE TITLE
Set up a timezone table/map of all participants 

### ISSUE THREAD

**Issue by Mariatta** [python/core-sprint#16]
Perhaps we can use something like https://timezone.io/team/buffer 

Open to other suggestions

**Comment by terryjreedy** [comment]
I left the signup time map blank because I am retired and potentially available most any time I am awake, which itself is a bit variable.  It would be nice to be able to indicate presence or availability in real time.

**Comment by Mariatta** [comment]
I've posted participants and their timezones in https://python-core-sprint-2020.readthedocs.io/participants.html

No as fancy as timezone.io of course. But perhaps this is good for now.
