### ISSUE TITLE
Idea: design sprint swag like t-shirt/mug for participants

### ISSUE THREAD

**Issue by Mariatta** [python/core-sprint#17]
I think it would be cool to design some kind of swag to be sent out to sprint participants. e.g. t-shirt, mug, sticker sheet, pin, etc. Not sure if this is something people would be interested in, and whether we could get the fund for it.

**Comment by gvanrossum** [comment]
I'm personally partial to T-shirts. :-)

**Comment by gpshead** [comment]
With services like cafepress.com, I believe they print all of these items and much more on demand, so we could likely make all of the above available to whomever wants them.

**Comment by taleinat** [comment]
A coffee mug and T-shirt would be nice :)

**Comment by Mariatta** [comment]
We got sponsorship confirmed just last night, but at this stage it's a bit late to design anything. So perhaps this is an idea for future sprints or for the future language summit.
