### ISSUE TITLE
Create a central editable collaborative notes of sprint project

### ISSUE THREAD

**Issue by Mariatta** [python/core-sprint#2]
From [Discourse](https://discuss.python.org/t/2020-core-dev-sprint-virtual-sprinting-sessions/3947/16), it was suggested to "set up some kind of easy-to-edit central collaborative notes/links/tasks document with a schedule and notes broken up by days, where it’s easy to jump to the section about a particular day (Google Docs or something like it)"

What will we use? GDocs? Hackmd? 

From @brainwane on [Discourse](https://discuss.python.org/t/2020-core-dev-sprint-virtual-sprinting-sessions/3947/16):
 **Prep for discoverability** – participants need to know who’s working on what so they can work together. But this is harder to serendipitously find out remotely. And some participants are reluctant to commit to a project ahead of time, or forget to update any central board/wiki page/doc as they work. So:
- if you can, come to a rough consensus at least a few days before the event, agreeing on a few goals you want to achieve, and getting a few people to step up as topic leads; those topic leads should set up some spaces (Zulip threads, videocall rooms, etc., whatever seems good to them) for work on those topics
- privately, give participants a list of other participants at least a few days ahead of time
- set up some kind of easy-to-edit central collaborative notes/links/tasks document with a schedule and notes broken up by days, where it’s easy to jump to the section about a particular day (Google Docs or something like it)
- if a voice or IRC/Zulip conversation gets to where people are making decisions or sharing key info, have a notetaker put notes in that central doc
- each day, not in a big meeting but as a series of quick small conversations, have a person check in on what everyone’s working on, and take some brief notes and put them in that central document

**Comment by ejodlowska** [comment]
I recall that folks didn't take to HackMD. Maybe google docs is more universally accepted?

**Comment by gvanrossum** [comment]
Would I be out of line to suggest Dropbox Paper? It requires a (free) Dropbox account to edit, so that's a Con. But it has a nifty ToC feature in the left side bar, which I don't think GDocs has, so that's a Pro.

**Comment by Mariatta** [comment]
Thanks for suggesting DropBox Paper, Guido. Not an issue for us. We discussed this today, and considering that core devs have used Google Docs last year for the sprint and it seemed to work fine, we decided to continue using Google Docs for now.

You can add ToC in Google Docs: https://support.google.com/docs/answer/116338?co=GENIE.Platform%3DDesktop&hl=en

**Comment by Mariatta** [comment]
I've published the projects list in https://python-core-sprint-2020.readthedocs.io/projects.html, based on current signups.

Perhaps we can create a separate Google Docs for each project listed, and link from that page?

**Comment by ejodlowska** [comment]
That sounds reasonable @Mariatta.

If you like, I can create a sprint folder on the PSF GSuite and then create a doc for each project within that folder. Not sure if you want that folder accessible to anyone or just to the core devs participating. Let me know I can work on that!

**Comment by Mariatta** [comment]
Thanks @ejodlowska! Yes it would be great if you can create the sprint folder with each docs. For now, let's restrict access to those who have signed up for the sprint. Thanks!

**Comment by ejodlowska** [comment]
Done! I shared it with @Mariatta and @aeros for now. Do y'all think I should share it with the emails I have for core devs based on emails used to subscribe to python-committers?

**Comment by Mariatta** [comment]
I think we can grant access to everyone registered to the sprint. I produce a comma separated list of all participants registered in the RSVP form.

**Comment by Mariatta** [comment]
Docs have been created and I believe those who signed up has been granted access. Please just ask if you don't have access yet.
