### ISSUE TITLE
Sprint activity: Tech Check before sprint starts

### ISSUE THREAD

**Issue by Mariatta** [python/core-sprint#20]
Idea from Barry: We should definitely have a pre-sprint "tech day" where people can install, check, and fix whatever tools they need to participate.

We will schedule some time on Sunday for the tech check.

The relevant techs and tools are:
 
- Discord
- Zoom, for meetings and all hands
- Note taking app, Google Docs
- Calendar, Google Calendar

**Comment by Mariatta** [comment]
@aeros said he would be available between 3 PM - midnight US Eastern time on Sunday Oct 18.
@aeros Can you write up more details about tech check session? How will this work?

**Comment by taleinat** [comment]
Ping, @aeros?

**Comment by aeros** [comment]
I just came back in town from a flight, currently catching up on some college work and then I'll update the docs to include some more details about the "tech check" day/session as soon as I'm able to.

**Comment by aeros** [comment]
Closed via https://github.com/python/core-sprint/pull/55.
