### ISSUE TITLE
Grant access for "notes" docs to all participants.

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/core-sprint#36]
I tried accessing one of the notes docs (in this case the one for ["C-API/subinterpreters"](https://docs.google.com/document/d/1tkaE7tgNjlUxprRSUZm0L8o3JRQldNFiOTV1alkVEHI/edit?usp=sharing)) and got a permission-denied message, along with the option to request access.  I have done so for that one doc, but would like access to all the notes docs (without having to request access for each).

I would expect others to want the same and it would probably make sense to give access to all registered participants.

**Comment by Mariatta** [comment]
Yes the plan is to grant access to all the notes to everyone registered for the sprint. We haven't gotten around doing it yet :) so now all the notes are empty.

**Comment by ericsnowcurrently** [comment]
+1

**Comment by Mariatta** [comment]
You should have access now.
