### ISSUE TITLE
Create a shared calendar

### ISSUE THREAD

**Issue by warsaw** [python/core-sprint#52]
Please consider creating a shared calendar that we can subscribe to.  This calendar should hold all the events that are currently planned, and individual projects should be able to add meeting times and such to it.

**Comment by Mariatta** [comment]
I believe everyone participating has already been given access to the shared google calendar titled "Python Virtual Core Dev Sprint". This is the link: https://calendar.google.com/calendar/embed?src=c_qiar6rspbhh64kb4vrv52seaok%40group.calendar.google.com&ctz=America%2FVancouver

I will add it to the doc.

**Comment by warsaw** [comment]
Thanks @Mariatta - can you please add instructions for how to add this to your calendar app (e.g. on macOS)?  I couldn't find a way to do that.

**Comment by Mariatta** [comment]
Ok let me try to find the instructions from Google. But in the meantime, you can see the calendar here: https://python-core-sprint-2020.readthedocs.io/schedule.html (it just finished building, so you may need to do a hard refresh).

**Comment by Mariatta** [comment]
@warsaw Are you using Apple Calendar? Can you try these steps? https://support.google.com/calendar/answer/99358?co=GENIE.Platform%3DDesktop&hl=en

**Comment by warsaw** [comment]
@Mariatta Yes, that does help, but it's not enough.  Here are the steps that worked for me:

* Open the Python Virtual Sprint calendar in a browser while logged into Google
* Click the little `+` symbol in the lower right corner of the calendar and answer "yes" to add this calendar to your Google calendars
* Go to the sync page referenced off the above link and find the Python Virtual Sprint calendar; enable sync'ing this one
* Now go to your Google calendar account in macOS Calendar.app.  You should find the Python Virtual Sprint calendar there, enable it.

So now the sprint calendar should show up in Calendar.app.

Thanks!

**Comment by Mariatta** [comment]
I think this is resolved.
